name: CI
on: [push, pull_request]
jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: docker exec bearamos/backend-desafio-5 npm run test